/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PersonkortRouteImport } from './routes/personkort'
import { Route as IndexRouteImport } from './routes/index'

const PersonkortRoute = PersonkortRouteImport.update({
  id: '/personkort',
  path: '/personkort',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/personkort': typeof PersonkortRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/personkort': typeof PersonkortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/personkort': typeof PersonkortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/personkort'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/personkort'
  id: '__root__' | '/' | '/personkort'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonkortRoute: typeof PersonkortRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/personkort': {
      id: '/personkort'
      path: '/personkort'
      fullPath: '/personkort'
      preLoaderRoute: typeof PersonkortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonkortRoute: PersonkortRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
