/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonkortFnrRouteImport } from './routes/personkort.$fnr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonkortFnrRoute = PersonkortFnrRouteImport.update({
  id: '/personkort/$fnr',
  path: '/personkort/$fnr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/personkort/$fnr': typeof PersonkortFnrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/personkort/$fnr': typeof PersonkortFnrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/personkort/$fnr': typeof PersonkortFnrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/personkort/$fnr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/personkort/$fnr'
  id: '__root__' | '/' | '/personkort/$fnr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonkortFnrRoute: typeof PersonkortFnrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personkort/$fnr': {
      id: '/personkort/$fnr'
      path: '/personkort/$fnr'
      fullPath: '/personkort/$fnr'
      preLoaderRoute: typeof PersonkortFnrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonkortFnrRoute: PersonkortFnrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
